spring:
  application:
    name: springboot-init
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://$MYSQL_IP:$MYSQL_PORT/$OPENAPI_BACKEND_DATABASE
    username: $MYSQL_USER
    password: $MYSQL_PASSWORD
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: $REDIS_PORT
    host: $REDIS_IP
    database: $REDIS_DATABASE
    password: $REDIS_PASSWORD
server:
  port: $OPENAPI_BACKEND_PORT
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为

# 这段配置仅供测试，实际应该根据登录用户获取对应的 ak、sk
openapi:
  client:
    access-key: testAk
    secret-key: testSk
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://$NACOS_IP:$NACOS_PORT
